Name:             app-ingress
Namespace:        harvest-harvest
Address:          a7980996516fe41288fb7ebe2ac07b0e-f30992e8ce88f5a7.elb.eu-west-3.amazonaws.com
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  harvest-app-tls terminates harvest-app-ingress.inovshop-dev.com,harvest-app.inovshop.com
Rules:
  Host                                  Path  Backends
  ----                                  ----  --------
  harvest-app-ingress.inovshop-dev.com  
                                           app-harvest-service:8000   10.2.28.239:80)
  harvest-app.inovshop.com              
                                           app-harvest-service:8000   10.2.28.239:80)
Annotations:                            cert-manager.io/cluster-issuer: letsencrypt-prod
                                        kubernetes.io/ingress.class: nginx
                                        kubernetes.io/tls-acme: true
                                        nginx.ingress.kubernetes.io/client-body-buffer-size: 400m
                                        nginx.ingress.kubernetes.io/proxy-body-size: 400m
