Name:             website-ingress
Namespace:        harvest-harvest
Address:          35.180.45.204
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  harvest-website-tls terminates harvest-ingress.inovshop-dev.com,harvest.inovshop.com
Rules:
  Host                              Path  Backends
  ----                              ----  --------
  harvest-ingress.inovshop-dev.com  
                                       website-harvest-service:9001   10.2.8.221:5000)
  harvest.inovshop.com              
                                       website-harvest-service:9001   10.2.8.221:5000)
Annotations:                        cert-manager.io/cluster-issuer: letsencrypt-prod
                                    kubernetes.io/ingress.class: nginx
                                    kubernetes.io/tls-acme: true
                                    nginx.ingress.kubernetes.io/client-body-buffer-size: 400m
                                    nginx.ingress.kubernetes.io/proxy-body-size: 400m
