ame:             api-ingress
Namespace:        omni-omni
Address:          35.180.45.204
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  omni-api-tls terminates omni-api-ingress.inovshop-dev.com,omni-api.inovshop.com
Rules:
  Host                               Path  Backends
  ----                               ----  --------
  omni-api-ingress.inovshop-dev.com  
                                        api-omni-service:9000   10.2.5.132:7000)
  omni-api.inovshop.com              
                                        api-omni-service:9000   10.2.5.132:7000)
Annotations:                         kubernetes.io/ingress.class: nginx
                                     kubernetes.io/tls-acme: true
                                     nginx.ingress.kubernetes.io/client-body-buffer-size: 400m
                                     nginx.ingress.kubernetes.io/proxy-body-size: 400m
                                     nginx.ingress.kubernetes.io/proxy-connect-timeout: 3600s
                                     nginx.ingress.kubernetes.io/proxy-read-timeout: 3600s
                                     nginx.ingress.kubernetes.io/proxy-send-timeout: 3600s